export const example = {
    "uz":{
        meat_title:"Kolbasa sexi uchun quvvati 50 kVt",
        meat_text_1:"Go‘sht qiymalagich - 14.5 kv",
        meat_text_2:"Defoster (go‘sht muzlatish uskunasi) - 0.6 kVt",
        meat_text_3:"Shprits uskunasi (kolbasa qadoqlagich) -4.5 kVt",
        meat_text_4:"Issiqlik kamerasi - 6.5 kVt",
        machine_title:"Tikuv sexi uchun quvvati 100 kVt",
        usage:"Maxsulotlarning qo'llanilish soxasi",
        factory:"Barcha turdagi zavodlar uchun",
        petrol:"Yonilg'i quyish shaxobchasi",
        super:"Supermarket",
        home:"Axoli yashash xonadonlari",
        restoran:"Restoranlar",
        kino:"Kinotetr",
        firm:"Ishlab chiqarish sexlari",
        school:"Maktablar",
        hospital:"Kasalxonalar",
    },
    "ru":{
        meat_title:"Потребление Колбасного цеха на 50 Квт",
        machine_title:"Текстильная промышленность на 100 Квт",
        usage:"Область применения продукции",
        factory:"Для всех видов растений",
        petrol:"Топливный бак",
        super:"Супермаркет",
        home:"Жилые квартиры",
        restoran:"Рестораны",
        kino:"Кино",
        firm:"Производственные цеха",
        school:"Школы",
        hospital:"Больницы",

    }
}